# To re-encrypt any sops-encrypted secrets files after changing keys in this file, use:
#   sops updatekeys secrets/host/filename.yaml
# ? ref: https://github.com/anoadragon453/dotfiles/commit/894827f3013d87e49a6ae1e22ea8621c7116654e#diff-a566a585e0557100ce61bf3777660a8aa5e3e56e7e89836392469bd5163663c1
keys:
  # Key fingerprints of administrators of the system.
  #
  # To add a new entry:
  #
  # 1. Create a directory to store your age keys: `mkdir -p ~/.config/sops/age`
  # 2. Generate an age key on your computer: `age-keygen -o ~/.config/sops/age/keys.txt`
  # 3. Place the public key that you're given here. If you need to find it again, use:
  #    `age-keygen -y ~/.config/sops/age/keys.txt`
  - &user_fabrice_primary age1pe3qfuzzgkmfn0yg9ezehw2kkftaj30evvck705hs9gmdv3vhqdsu44hl2
  # Key fingerprints for hosts in my infrastructure.
  #
  # To add a new entry:
  #
  # 1. Build a VM variant of the host: `nixos-rebuild --flake .#hostname build-vm
  # 2. Boot the VM: `QEMU_NET_OPTS="hostfwd=tcp::2222-:22" ...`
  # 3. SSH in: `ssh -p2222 root@localhost`
  # 4. Extract the public key: `cat /var/lib/sops-nix/key.txt` and add it below.
  # 5. This file should be copied to the same location on the host before deploying it:
  #    ssh root@REMOTE_HOST 'mkdir -p /var/lib/sops-nix' \
  #        && ssh -p2222 root@localhost 'cat /var/lib/sops-nix/key.txt' \
  #        | ssh root@REMOTE_HOST 'cat > /var/lib/sops-nix/key.txt'
  - &vm age10vwwse7fjh75etda00kxtsxatwq60uvy6f4vsxkpx9xm8nz5hquqn7tgck
  - &legacy_vm age1s4uqdm7hmaev4h2m0sf7qk5wxddke6rhem0gqeegpgpdav04fyqq5r9fkn
# This section determines the keys that secrets under certain folder paths are encrypted for.
# (AKA which keys (key_groups) can decrypt which secrets (path_regex))  
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    # note: you MUST specify both `pgp` and `age` fields, even if one is empty.
    - pgp: []
      age:
      - *user_fabrice_primary
      - *vm
      - *legacy_vm
