---

#! To add - MACHINE - keys:
# 1. Generate new key on another Nix-machine: nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
# 2. Add a new entry for the machine and specify this in the creation rules by adding the public key, ie. age1gvccm4tcncykmegm0x2qthdku748p8s4dcwh99c80llnd4ly0eaqevpdk2
# 3a. Decryot and encryot the secrets:
#   - sops -d -i secrets/super_secrets.yaml # decrypt
#   - sops -e -i secrets/super_secrets.yaml # encrypt
# or
# 3b. Update secret
#   - sops updatekeys secrets/super_secrets.yaml
#! To add USER keys:
# 1. Create a directory to store your age keys: mkdir -p ~/.config/sops/age
# 2. Place the private key(s) of yours from Password manager (ie. 1Password) into the file ~/.config/sops/age/keys.txt
# 3. Follow steps 2 - from the MACHINE guide

# ? ref: https://github.com/anoadragon453/dotfiles/commit/894827f3013d87e49a6ae1e22ea8621c7116654e#diff-a566a585e0557100ce61bf3777660a8aa5e3e56e7e89836392469bd5163663c1
keys:

  - &user_fabrice_primary age1pe3qfuzzgkmfn0yg9ezehw2kkftaj30evvck705hs9gmdv3vhqdsu44hl2
  - &machine_revan age10vwwse7fjh75etda00kxtsxatwq60uvy6f4vsxkpx9xm8nz5hquqn7tgck
  - &machine_maul age1gvccm4tcncykmegm0x2qthdku748p8s4dcwh99c80llnd4ly0eaqevpdk2
  - &machine_legacy_vm age1s4uqdm7hmaev4h2m0sf7qk5wxddke6rhem0gqeegpgpdav04fyqq5r9fkn
# This section determines the keys that secrets under certain folder paths are encrypted for.
# (AKA which keys (key_groups) can decrypt which secrets (path_regex))  
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    # note: you MUST specify both `pgp` and `age` fields, even if one is empty.
    - pgp: []
      age:
      - *user_fabrice_primary
      - *machine_revan
      - *machine_maul
      - *machine_legacy_vm
