# https://taskfile.dev

version: "3"

vars: {}

tasks:

############## & if not built system yet,m run: 'nix-shell -p go-task' to load Go Tasks!

  default:
    cmds:
      - task --list-all
    silent: true

  nix-flake-update:
    desc: Update flake system
    cmds:
      - nix flake update

  nix-host-redeemer:
    desc: Apply configuration --> host / redeemer
    cmds:
      - sudo nixos-rebuild switch --flake .#redeemer

  nix-host-current:
    desc: Apply configuration --> host / $(hostname)
    cmds:
      - sudo nixos-rebuild switch --flake .#    
 
  nix-user-fabrice:
    desc: Apply configuration --> user / fabrice
    cmds:
      - nix build .#homeManagerConfigurations.fabrice.activationPackage 
      - ./result/activate

  nix-gc:
    desc: Clean previous Nix generations and display results
    cmds:
      - nix-collect-garbage --delete-old
      - duf

  nix-flake-selective-update:
    desc: Select individual package sources for update from the flake
    cmds:
      - nix run github:vimjoyer/nix-update-input

  nix-flake-meta:
    desc: Check flake metadata
    cmds:
      - nix flake metadata

  nix-flake-full:
    desc: Apply configuration using $(hostname) and 'fabrice' username
    cmds:
      - task: nix-flake-update
      - task: nix-host-current
      - task: nix-user-fabrice
      - task: nix-gc

